ALTER TABLE "public"."Budget" ALTER COLUMN "totalPerPerson" SET DATA TYPE DECIMAL(65,30);
ALTER TABLE "public"."Expense" ALTER COLUMN "cost" SET DATA TYPE DECIMAL(65,30);
ALTER TABLE "public"."ExpenseSplit" ALTER COLUMN "share" SET DATA TYPE DECIMAL(65,30);
